@startuml

folder 楽器、音源上での作業 {
    rectangle r1 [
        <b>音色</b>
        ====
        シンセサイザーを使用した音色の作成
    ]

    note as n1 
        <b>エンベロープの調整</b>
        ----
        アーティキュレーションや
        グルーヴ等、リズムに沿った
        音価へと調整
    end note
    

    r1 .right. n1
}


folder DAW、MIDIシーケンサでの演奏収録 {
    rectangle r2 [
        <b>リック</b>
        ====
        細かいリック(フレーズ)の素片、
        ドラムパターンなど
        ----
        リックの場合は音律(コードやスケール)的要素と、
        強弱陰影アクセントなどのリズム的要素はそれぞれ別に管理、
        編集出来なければライブラリとして汎用的にはならない。
        ----
        ドラムパターンにおいても同様に、
        叩く楽器と、
        強弱陰影アクセントなどは分ける。
    ]
    note as n2
        <b>アーティキュレーションの付与</b>
        ----
        ピッチベンドや音色変化などの
        アーティキュレーション(演奏表現)。
        リックやリズムパターンが
        実際に演奏される際に装飾として
        付与される。
    end note

    rectangle r3 [
        <b>フィルへ変形</b>
        ----
        コード変遷などの際には、変遷の両者を繋ぐ役割の
        フレーズ(フィル)が存在する。
        すなわちリックやリズムパターンは採用時に都度その場に
        ふさわしい形に変えて楽曲へ組み込まれる。
    ]

    note as n3
        <b>グルーヴの付与</b>
        ----
        フレーズ、
        アーティキュレーション、
        リズムなど、
        各パートが同時に演奏し
        アンサンブルになった結果、
        その全体に顕れるノリ
    end note

    n1 .up. r2
    r2 .. n2
    r3 .. n2

}

folder 譜面、手書き作業 {

    rectangle r4 [
        <b>コード進行、拍子</b>
        ====
        より高階にあたるコード進行、
        リズム(拍子)の変遷など
    ]

    rectangle r5 [
        <b>構成、調</b>
        ====
        最上位の
        転調や曲の構成など
    ]
}

r2 .. n3
r3 .. n3





r1 --> r2
r2 --> r3
r3 -down-> r4
n3 .down. r4
r4 --> r5




@enduml

