= MIDI シンセサイザーエディタ

== 音源の音色エディットに関する問題点

音源の音色のエディットは、原則的にシンセサイザー本体の操作パネルを使用する。
音源がすぐ近くに配置できるのであればこれでも問題ないが、
現実には他に多数の音源、PC、ミキサー、エフェクターなど操作を必要とするものが
あるため、物理的に無理な場合が多い。
また、音源自体の操作性が非常に悪い場合や、そもそも音源に充分な操作パネルが
備わっておらず、専用のソフトを使ってエディットする必要がある機種も多数ある。
あるいは、音源のコントロールパネルのボタンやノブ類は、非常に過酷な使用条件に
晒されるため、耐久性やトラブルの面でも問題が多発する。
事実、個人的に所有するシンセ類は常にどこかの操作子がトラブルを抱えており、
万全の状態で作曲作業をした事自体ほとんど無い。

また、曲の作成時には作った音色をすぐに呼び出せるようにライブラリとして
整然と管理されていることが望ましいが、現状あまり汎用性の高い管理法を持つ
シーケンサがない。

製品としてはPC上のエディタ/ライブラリアンソフトが存在する。
音源のシンセサイズ方式はそれぞれ独自仕様なので、市販されている様々な音源に
専用の対応したエディタを持ち、サポートされていない音源であっても
ユーザーがある程度独自にエディタを作成できる。
ただし、ユーザー作成は機能に制限がありあまり満足のいくエディタを作成できない。
完全なエディタを作れない以上、結局音源を直接操作する必要が生じ、エディタソフトの
意味は無くなる。
また、専用エディタがサポートされていても、そもそもソフト自体の操作性がよろしくない。
PCの画面上に、実機のつまみを再現してそれをマウスのドラッグで操作するような
インターフェースが良好な操作性を生むはずは無い。

また、これらは原則としてMIDIシーケンサのメーカーが自社製シーケンサ専用に
作ったアプリケーションであるため、組み合わせ選択の自由が無い。
さらに、ずいぶん以前から新作リリースがされておらず、完全に陳腐化している。
現在はVSTプラグインにてエディタやライブラリ管理を行う方法が主流となっているが、
VSTプラグイン自体はSDKを使ってプログラミングする必要があり、ユーザーが自由に作成
できる類のものではないため、使用したい機器に対応したプラグインが存在しなければ
それまでとなる。

== 打開案

ダイレクトに音源の各音色パラメータへアクセス出来る、汎用的な物理コントローラがあると望ましい。
だが一方で、シンセサイザーはその音源方式が独特のデザインであり、そのため音色エディットに必要となる
パラメータも独特のものとなる傾向にある。
よって、小さい単位ブロックに分けられたユニットを適宜ユーザーが構築し、自身に必要となる
コントローラを構成できるような汎用的フォーマットがあると理想的。

ユーザーが自身の所有する音源への対応モジュールを作成できるエディット環境。
コントローラに音色ライブラリアン機能を持たせる。そのことにより、VSTプラグイン対応に関しても
個々の音源ごとに用意する必要はなく、コントローラに対するVSTプラグイン一つを作れば済む。

* 単体動作。本体にMIDI端子搭載
* 基本操作子 8 + 1ロータリーエンコーダ (計9ロータリー)
* 全ロータリーエンコーダ毎にLEDレベルメータ
* 液晶ディスプレイ、マトリクスセレクト用自照式ボタン等、汎用操作子
* エクスクルーシブデータマネージャ(ライブラリアン)
* 各シンセのエディタはユーザーが自身で作成可能 -> microSDカードへ保存(公式サイトに追加していくユーザー参加型)
* ライブラリアン情報にアクセスし音色をシーケンサ上から呼び出し可能にするVSTプラグイン


