:toc: left
:imagesdir: images

= アーティキュレーション付加MIDIコントローラ

== 概要

MIDIキーボードとシーケンサの間に挟む形で使用する形態のガジェット。
従来のMIDIキーボードではリアルタイム演奏での表現が不可能だった
ギターカッティング、ハンマリングやプリング、スライドなど
弦(フレットあり、なし)や吹奏楽器系の演奏表現を
MIDIキーボード演奏 -> リアルタイム変換 -> 音源 にて可能にするガジェット。

このガジェットは、

* 従来の(市販されている)音楽機材構成に加える事ができる
* 実現性が比較的容易(開発規模が比較的小さい)

といった現実的な側面がある。
反面、既存の作曲の問題や仕組みを変えることが出来るほどの
力は持たない。

== 対応予定演奏可能楽器の候補

* ギター/ベースなど、打弦楽器
** カッティング、コードストローク、ハンマリングオン/プリングオフ、スライド、ブリッジミュート
* ドラム/パーカッションなど、打楽器
** ロール、フラム、ゴーストノート、ミュート
* ブラス/木管など、吹奏楽器
** スラー、リップスラー

== 問題点の把握と解決指針

MIDIキーボードでキーボード系以外の楽器の演奏ニュアンス(アーティキュレーション)を
表現しようとすると、大きな制限がある。

例えば、ギターのカッティング時におけるコードストローク等を、
キーボードで再現演奏するのは非現実的といえる。
また、シーケンサで打ち込みをするのも多大な労力と時間が掛かる。

だがこれを、右手であらかじめ出す音を押さえておいて(まだこの時点ではノートonしない)

image::note-fig_01.svg[640, 480]

左手で音を出したいタイミングでキーを叩くとストロークがかかった状態で
時間差のあるノートonがなされる、という機構があればリアルタイム演奏が可能となる。

image::note-fig_02.svg[1024, 960]

左手で押さえるキーによって、アップストローク、ダウンストローク
ストロークの早さの選択などが行えると、MIDIキーボードでも
表現豊かなコードカッティング演奏が行える。
あるいはさらに、ペダルにハーフトーンやフルトーンのピッチアップやダウンを連動させておけば
ハンマリングやプリングの表現も可能になる。


ただ、こういった個別の挙動に対する対処法を機能として盛り込んでいくやり方では
どこまでも拡散してしまうため、もう少し抽象化する必要がある。
MIDIキーボードでの演奏では特に以下の2種類の変化を与える場面に大きな問題がある。

1. ピッチの伝達、変更方法
2. エネルギーの伝達、変更方法

アコースティックにおいてこの二つは演奏者が楽器に演奏の変更を加えると、
その過渡現象として、楽器から奏でられる音が変化していく。
演奏者が楽器にアーティキュレーションとなる入力を行うと、楽器の構造により出力は非線形の挙動をする。
だが、市販のコントローラやシーケンサではアーティキュレーションへの
対応がほとんど全くなされておらず、制作者は非効率的なデータの入力を
強いられることになる。

人間が操作すべきは、あくまで演奏ニュアンスを変化させる
情報のみにすべきであって、楽器自体に起こる過渡現象を
シーケンサに入力して再現するような事は不毛な作業でしかない。

道具は、あくまで人間の発想を具現化するためのものであるべきであるが、
現状は楽器に起こった過渡現象を逐一すべて入力しなければならない状況であり、
道具として意味をなしていない。
本ガジェットの目的は、この点をコントローラ側からのアプローチで
少しでも解消するためのものとなる。


== マイコンで実装するか、FPGA/CPLDも併用するか

本ガジェットはリアルタイムにMIDIを変換処理する必要がある。
そのため、ハードリアルタイム処理が絶対条件であり、
必然的に単体の専用ハードウェアによる実装となる。
専用ハードウェアであっても、マイコンによるソフトウェア処理では
ハードリアルタイムを達成できない可能性も生じる。
具体的なMIDIの処理内容は、そのほとんどが
数値テーブルを使ったマッピング変換になると予想されるため、
多数のテーブル変換器を持った回路をFPGAで実装し、
そのテーブル内容の編集やソース/ディスィネーション間の接続変更作業などの
リアルタイム性に関連しない部位にマイコンを使う形になる。

