= アーティキュレーション付加MIDIコントローラ

== 概要1

MIDIキーボードとシーケンサの間に挟む形で使用する形態のガジェット。
従来のMIDIキーボードではリアルタイム演奏での表現が不可能だった
ギターカッティング、ハンマリングやプリング、スライドなど
弦(フレットあり、なし)や吹奏楽器系の演奏表現を
キーボード演奏 + コントローラの操作にて可能にするガジェット。

このガジェットは、これまでの他の案と違い、

* 実現性が比較的容易
* 従来の(市販されている)音楽機材構成に加える事ができる

といった現実的な側面がある。
反面、既存の作曲の問題や仕組みを変えることが出来るほどの
力は持たない。

== 概要2

アコースティック楽器の演奏表現に関わってくる要素は
根本的に以下の二種類に分類される。

1. ピッチの伝達、変更方法
2. エネルギーの伝達、変更方法

この二つにおいて、演奏者が楽器に変更を加えると、
その過渡現象として、楽器から奏でられる音が変化していく。
人間が操作すべきは、あくまで演奏ニュアンスを変化させる
情報のみにすべきであって、楽器自体に起こる過渡現象を
シーケンサに入力して再現するような事は不毛な作業でしかない。
道具は、あくまで人間の発想を具現化するためのものであるべきであり、
最終結果を逐一入力しなければならないという現状は、
道具として意味をなしていない。
本ガジェットの目的は、この点を少しでも解消するためのものとなる。


== 演奏可能楽器の候補

* ギター/ベースなど、打弦楽器
* ドラム/パーカッションなど、打楽器
* ストリングスなど、擦弦楽器
* ブラス/木管など、吹奏楽器

== マイコンで実装するか、FPGA/CPLDも併用するか

本ガジェットはリアルタイムにMIDIを変換処理する必要がある。
そのため、ハードリアルタイム処理が絶対条件であり、
必然的に単体の専用ハードウェアによる実装となる。
専用ハードウェアであっても、マイコンによるソフトウェア処理では
ハードリアルタイムを達成できない可能性も生じる。
具体的なMIDIの処理内容は、そのほとんどが
数値テーブルを使ったマッピング変換になると予想されるため、
多数のテーブル変換器を持った回路をFPGAで実装し、
そのテーブル内容の編集やソース/ディスィネーション間の接続変更作業などの
リアルタイム性に関連しない部位にマイコンを使う形になる。

