= MIDI タイムコード表示機

ラックマウントあるいは壁掛け式の大型MIDIタイムコードディプスプレイ。
シーケンサからのMIDI TimeCode 同期信号を受信し、それを表示する。

他の案が技術的ハードルの高いものであり、実現の即時性に乏しいため、
短期に到達可能な小規模開発としての案。基礎技術獲得も兼ねる。

== 動機

ミュージシャンは、機材に対してハッタリを求める。
ミキサーのレベルメータ、オシロスコープによる位相表示、つまみやボタン類のLEDによる状態表示等。
派手で、賑やかで色とりどりの光モノや装飾をとても好む。 +
デザイン性や操作時のケレン味、光モノの過多等は、作曲の本質とはまったく関係しない。
まったく関係しないが、作業者のやる気にかなりの影響を与える。
作曲という作業は精神活動の連続であるため、やる気は実はとても重要な要素となる。

== MIDIタイムコード表示を選んだ理由

外部の単体レベルメータを製作しようとしても、MIDIシーケンサやミキサなどから
各チャンネルのレベルを送信するデータの共通フォーマットが存在しない。
その点、MIDIタイムコードは外部レコーダーとの同期用として共通フォーマットが存在するため、
既存の機材構成に組み込むことができる。

また、ニキシー管時計を見ていて、これがタイムコード表示だったらと考えた。

ただ残念ながら、ただ単にタイムコード(時、分、秒、フレーム)を表示するのは
あまり役には立たない。
理想を言えば、単なるタイムコード表示よりも、ロケーション表示
(つまり何小節の何拍、何ステップ)の方が作曲用途としては実用的。
ただし世のシーケンサ側に「現在ロケーション情報」を継続的に送信し続ける共通のフォーマットが
無いため、実現するとしても自前開発のシーケンサからのみの対応となる。
また、ロケーション情報を扱うのであれば、ロケータの操作そのものもコントロールできる
コントローラと一体にするべきともいえるし、そのあたりの市販品はすでに存在もしている。

== 仕様

* MIDIタイムコード(SMPTEも?)を受信し、現在のタイムを表示し続ける専用機
* ラックマウント型(2Uあたりのサイズを想定)で視認性が良好。
* 時(一桁)、分(二桁)、秒(二桁)、フレーム(二桁)の計七桁表示。それに加えて lock、stop、などの状態表示。
* 専用機のため、PCの画面にタイムコードを表示するスペースが不要となる。
* 表示デバイスには、当面はLEDを想定しているが、将来的にニキシー管の採用もあり。
* 搭載インターフェースは MIDI、USB-MIDI、(出来ればSMPTE)入力及び、各スルーアウト
* SMPTEのタイムコードへの対応は今後要検討。MIDI <--> SMPTE 相互変換をリアルタイムで行えてると従来のテープデバイスとの同期も取れて理想的だが、需要はかなり低い上に技術的ハードルも上がり、コストもかさむ。。
