= 卓上型ミニミキサー

== リモート需要向けサウンドガジェット

コロナによる外出自粛により、PC、スマホを使ったネットワーク上での
音声映像のリアルタイムコミュニケーションの需要が出てきた。
その際必要となるものとして、ヘッドホン(イヤホン)、マイク等が
挙げられるが、もう一つあれば便利なものとしてミキサーがある。

まず、考えられる使用用途として、ビジネス用とプライベート(ホビー)用に分けられるが、
ここではプライベート用を想定する。

ミキサーとしてはPCのサウンドボード上にある簡易ミキサー(あるいはソフトウェアミキサー)を
使うことでリモート用途として、通常の会話など最低限のことは出来るが、いろいろと制限も感じる。

=== 作曲、サウンドクリエイト用途

作曲の相談を仲間と行う時に以下のような欲求がある

* 話題に上がった曲を流したい
* 楽器を弾きながらコード進行やリズム、演奏ニュアンスの打ち合わせをしたい
* 音色やエフェクトワークなど、音そのもののイメージを言葉で伝えるのではなく、直にその音を聞かせる

=== 一般的な用途

* リモートに対応したボードゲームで、効果音をポン出しなど
(ただし、ポン出し追加となるとサンプリング機能や、効果音選択ボタンを追加となるためコスト増)

=== ビジネス用途

反して、ビジネス用ではミキサーの必要性がほとんど無いと思われる。

* 議事録用に、出力をモニター以外にレコーダーへ分配など

ただし議事録は、音声からテキストへ起こすのが大変なので、これだけではあまり意味はない。
やるとするならば、

a. 話題別にタイムラインへマーカーをつける(会議中におおよそ手動でつける、あるいは後にじっくりとその場所を修正もできる)
b. 発言人物別の音声トラック切り分け
c. 音声->テキスト起こし

a.を実現しようとする時点で、すでに会議アプリを独自に開発しなければあまり意味がない。 +
b.は、チャットアプリが発言者別の音声をパラ出しする機能があらかじめ備わっていないといけない。
これは既出のアプリでできるのかどうか不明。一度ミックスしてしまった音声を声紋分析などで分けるのは、かなり難しい。 +
c.も、ミキサーとは異なる、機械学習を用いた機能が備わっていないと実用的ではない上に、
音声認識は既存のアルゴリズム(アレクサ、siriなど)を利用するだけに止まることになる。 +

